# Generated by Django 5.2.11 on 2026-02-05 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('language_preference', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('partner_inquiry', models.BooleanField(default=False)),
                ('partner_full_name', models.CharField(blank=True, max_length=255)),
                ('partner_age', models.IntegerField(blank=True, null=True)),
                ('partner_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('source', models.CharField(max_length=100)),
                ('sub_source', models.CharField(blank=True, max_length=100)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=20)),
                ('next_action_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20, null=True)),
                ('next_action_description', models.TextField(blank=True, null=True)),
                ('treatment_interest', models.TextField(help_text='Comma separated values')),
                ('document', models.FileField(blank=True, null=True, upload_to='lead_documents/')),
                ('book_appointment', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_description', models.TextField(blank=True)),
                ('campaign_objective', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adv_accounts', models.IntegerField(blank=True, null=True)),
                ('campaign_mode', models.IntegerField(choices=[(1, 'Organic Posting'), (2, 'Paid Advertising')])),
                ('campaign_content', models.TextField(blank=True)),
                ('selected_start', models.DateTimeField()),
                ('selected_end', models.DateTimeField()),
                ('enter_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(help_text='Audience list name or identifier', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_configs', to='restapi.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSocialMediaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_configs', to='restapi.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='restapi.clinic'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.clinic')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
