# Generated by Django 5.2.8 on 2026-02-10 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_description', models.TextField(blank=True)),
                ('campaign_objective', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adv_accounts', models.IntegerField(blank=True, null=True)),
                ('campaign_mode', models.IntegerField(choices=[(1, 'Organic Posting'), (2, 'Paid Advertising')])),
                ('campaign_content', models.TextField(blank=True)),
                ('selected_start', models.DateTimeField()),
                ('selected_end', models.DateTimeField()),
                ('enter_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restapi_campaign',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(help_text='Audience list name or identifier', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_configs', to='restapi.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSocialMediaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_configs', to='restapi.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='restapi.clinic'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.clinic')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('language_preference', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('partner_inquiry', models.BooleanField(default=False)),
                ('partner_full_name', models.CharField(blank=True, max_length=255)),
                ('partner_age', models.IntegerField(blank=True, null=True)),
                ('partner_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('source', models.CharField(max_length=100)),
                ('sub_source', models.CharField(blank=True, max_length=100)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=20)),
                ('next_action_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20, null=True)),
                ('next_action_description', models.TextField(blank=True, null=True)),
                ('treatment_interest', models.TextField(help_text='Comma separated values')),
                ('document', models.FileField(blank=True, null=True, upload_to='lead_documents/')),
                ('book_appointment', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='restapi.employee')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='restapi.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='restapi.clinic')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.department')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_leads', to='restapi.employee')),
            ],
            options={
                'db_table': 'restapi_lead',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(choices=[('healthcare', 'Healthcare'), ('ivf', 'IVF & Fertility'), ('pharma', 'Pharma / Biotech'), ('diagnostics', 'Diagnostics Lab'), ('corporate', 'Corporate Sales'), ('education', 'Education / Training'), ('saas', 'SaaS / Technology'), ('manufacturing', 'Manufacturing'), ('research', 'Research'), ('government', 'Government'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='restapi.clinic')),
            ],
            options={
                'db_table': 'restapi_pipeline',
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=255)),
                ('stage_type', models.CharField(choices=[('lead', 'Lead'), ('engagement', 'Engagement'), ('conversion', 'Conversion'), ('closure', 'Closure')], max_length=20)),
                ('stage_status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=20)),
                ('color_code', models.CharField(default='#EBFAEF', max_length=10)),
                ('entry_rule', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=20)),
                ('stage_order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='restapi.pipeline')),
            ],
            options={
                'db_table': 'restapi_pipeline_stage',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='StageField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='restapi.pipelinestage')),
            ],
            options={
                'db_table': 'restapi_stage_field',
            },
        ),
        migrations.CreateModel(
            name='StageRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('appointment', 'Appointment'), ('custom', 'Custom Action')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('auto_move', models.BooleanField(default=False)),
                ('allow_manual_move', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restapi.pipelinestage')),
            ],
            options={
                'db_table': 'restapi_stage_rule',
            },
        ),
    ]
