# Generated by Django 5.2.8 on 2026-01-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='equipment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='restapi.equipmentdetails'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='restapi.equipments'),
        ),
        migrations.AlterField(
            model_name='parametervalues',
            name='content',
            field=models.TextField(),
        ),
    ]
