# Generated by Django 5.2.8 on 2026-01-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_department_modified_at_equipmentdetails_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
