# Generated by Django 5.2.8 on 2026-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_parameters_config_parametervalues_equipment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
