# Generated by Django 5.2.8 on 2026-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_parameters_deleted_at_parameters_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
