# Generated by Django 5.2.11 on 2026-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='post_id',
            field=models.CharField(blank=True, help_text='Stores social media post ID (Facebook / LinkedIn / Instagram)', max_length=255, null=True),
        ),
    ]
