# Generated by Django 5.2.8 on 2026-01-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_parameters_deleted_at_parameters_is_deleted'),
    ]

    # NOTE:
    # This migration originally renamed SubTask.description -> SubTask.name
    # and added Task.name.
    #
    # These changes are already reflected in the database and models.
    # Keeping this migration as a NO-OP avoids migration state conflicts.

    operations = []
