# Generated by Django 5.2.8 on 2025-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_clinic_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipmentdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
