# Generated by Django 5.2.8 on 2026-02-12 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_ticket_deleted_at_ticket_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('use_case', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_templates', to='restapi.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.employee')),
            ],
            options={
                'db_table': 'restapi_template_mail',
            },
        ),
        migrations.CreateModel(
            name='TemplateMailDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='template_mail_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restapi.templatemail')),
            ],
            options={
                'db_table': 'restapi_template_mail_document',
            },
        ),
        migrations.CreateModel(
            name='TemplateSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('use_case', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='restapi.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.employee')),
            ],
            options={
                'db_table': 'restapi_template_sms',
            },
        ),
        migrations.CreateModel(
            name='TemplateSMSDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='template_sms_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restapi.templatesms')),
            ],
            options={
                'db_table': 'restapi_template_sms_document',
            },
        ),
        migrations.CreateModel(
            name='TemplateWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('use_case', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='restapi.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.employee')),
            ],
            options={
                'db_table': 'restapi_template_whatsapp',
            },
        ),
        migrations.CreateModel(
            name='TemplateWhatsAppDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='template_whatsapp_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restapi.templatewhatsapp')),
            ],
            options={
                'db_table': 'restapi_template_whatsapp_document',
            },
        ),
    ]
