# Generated by Django 5.2.8 on 2026-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_rename_description_subtask_name_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='total_tracked_sec',
            field=models.IntegerField(default=0),
        ),
    ]
