# Generated by Django 5.2.11 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_campaign_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='post_id',
            field=models.CharField(blank=True, help_text='Stores social media post ID', max_length=255, null=True),
        ),
    ]
