# Generated by Django 5.2.11 on 2026-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_campaignsocialmediaconfig_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public image URL attached to social media posts', max_length=2000, null=True),
        ),
    ]
