# Generated by Django 5.2.8 on 2025-12-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_clinic_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('equipment', 'parameter_name', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='parameters',
            index=models.Index(fields=['equipment', 'parameter_name', 'created_at'], name='restapi_par_equipme_77d582_idx'),
        ),
    ]
