# Generated by Django 5.2.8 on 2026-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_templatemail_templatemaildocument_templatesms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_mode',
            field=models.IntegerField(choices=[(1, 'Organic Posting'), (2, 'Paid Advertising'), (3, 'Email Campaign')]),
        ),
    ]
