# Generated by Django 5.2.8 on 2025-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_parameters_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
