# Generated by Django 5.2.8 on 2025-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_equipments_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
