# Generated by Django 5.2.8 on 2026-02-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_leadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_labs', to='restapi.employee'),
        ),
        migrations.AddField(
            model_name='lab',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='restapi.clinic'),
        ),
        migrations.AddField(
            model_name='lab',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='restapi.department'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='title',
            field=models.CharField(blank=True, help_text='Short title for the note.', max_length=255, null=True),
        ),
    ]
