# Generated by Django 5.2.8 on 2026-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_lab_assigned_to_lab_clinic_lab_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
