# Generated by Django 5.2.8 on 2025-12-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_equipments_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parameters',
            name='restapi_par_equipme_77d582_idx',
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parameters',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='parameters',
            index=models.Index(fields=['equipment', 'parameter_name'], name='restapi_par_equipme_4bdc44_idx'),
        ),
        migrations.AddIndex(
            model_name='parameters',
            index=models.Index(fields=['parent_id'], name='restapi_par_parent__fedac5_idx'),
        ),
    ]
