# Generated by Django 5.2.8 on 2026-01-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_eventequipment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_events', to='restapi.department')),
            ],
            options={
                'db_table': 'task_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
