# Generated by Django 5.2.8 on 2025-12-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_remove_parameters_restapi_par_equipme_77d582_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='parameters',
            name='restapi_par_equipme_4bdc44_idx',
        ),
        migrations.RemoveIndex(
            model_name='parameters',
            name='restapi_par_parent__fedac5_idx',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='content',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='restapi.parameters'),
        ),
    ]
