# Generated by Django 5.2.8 on 2026-02-14 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_lab_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('post_id', models.CharField(blank=True, help_text='ID returned by Facebook/LinkedIn after successful post', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When LMS triggered the post')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When Zapier callback updated the status', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='restapi.campaign')),
            ],
        ),
    ]
