# Generated by Django 5.2.11 on 2026-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mailchimp_campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='enter_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='selected_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='selected_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
