# Generated by Django 5.2.8 on 2026-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_task_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment_parameter_value',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
