# Generated by Django 5.2.11 on 2026-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_campaign_mailchimp_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailconfig',
            name='insights',
            field=models.JSONField(blank=True, help_text='Cached Mailchimp campaign insights stored as a single JSON dict. Keys: emails_sent, opens, open_rate, clicks, click_rate, bounces, unsubscribes, last_open, last_click, synced_at. Saved when GET /api/campaigns/<id>/mailchimp-insights/ is called. Read by CampaignListAPIView and CampaignGetAPIView as a fallback so the dashboard always shows the last known data.', null=True),
        ),
    ]
