# Generated by Django 5.2.8 on 2026-02-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_campaignsocialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
