# Generated by Django 5.2.8 on 2026-01-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_environment_parameter_value_log_time_and_more'),
    ]

    operations = [
        # REMOVE old direct FK
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),

        # ADD Task → Task_Event (TEMP NULL)
        migrations.AddField(
            model_name='task',
            name='task_event',
            field=models.ForeignKey(
                to='restapi.task_event',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                null=True,
                blank=True
            ),
        ),

        # ADD Task_Event → Event (TEMP NULL)
        migrations.AddField(
            model_name='task_event',
            name='event',
            field=models.ForeignKey(
                to='restapi.event',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='task_events',
                null=True,
                blank=True
            ),
        ),
    ]
