# Generated by Django 5.2.8 on 2026-02-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mailchimp', 'Mailchimp')], max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marketing_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
