# Generated by Django 5.2.11 on 2026-03-17 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_campaignemailconfig_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('collect_on', models.CharField(choices=[('google', 'Google'), ('form', 'Feedback Form'), ('both', 'Both')], max_length=20)),
                ('mode', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='restapi.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.lead')),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restapi.reviewrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRequestLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sent', models.BooleanField(default=False)),
                ('review_submitted', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.lead')),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='restapi.reviewrequest')),
            ],
        ),
    ]
