# Generated by Django 5.2.8 on 2026-01-21 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_remove_task_event_task_task_event_task_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='restapi.task_event'),
        ),
        migrations.AlterField(
            model_name='task_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_events', to='restapi.event'),
        ),
    ]
