# Generated by Django 5.2.8 on 2026-01-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_alter_task_task_event_alter_task_event_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_event',
            name='event',
        ),
    ]
