# Generated by Django 5.2.11 on 2026-03-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_reviewrequest_review_reviewrequestlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fb_campaign_id',
            field=models.CharField(blank=True, help_text='Facebook Ad Campaign ID created via API', max_length=100, null=True),
        ),
    ]
