# Generated by Django 5.2.11 on 2026-03-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_campaign_fb_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequestlead',
            name='sent_link',
            field=models.URLField(blank=True, help_text='The review link sent to the lead', null=True),
        ),
    ]
