# Generated by Django 5.2.8 on 2026-01-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_remove_task_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment_parameter_value',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='environment_parameter_value',
            table=None,
        ),
    ]
