# Generated by Django 5.2.11 on 2026-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_twiliocall_twiliomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_action_type',
            field=models.CharField(blank=True, choices=[('Follow Up', 'Follow Up'), ('Call Patient', 'Call Patient'), ('Book Appointment', 'Book Appointment'), ('Send Message', 'Send Message'), ('Send Email', 'Send Email'), ('Review Details', 'Review Details'), ('No Action', 'No Action')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('appointment', 'Appointment'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('cycle_conversion', 'Cycle Conversion'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
