# Generated by Django 5.2.8 on 2026-01-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_environment_parameter_value_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalues',
            name='equipment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.equipmentdetails'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.task_event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timer_status',
            field=models.CharField(default='IDLE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='environment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='environment_parameter',
            table=None,
        ),
        migrations.DeleteModel(
            name='AssigneeEvent',
        ),
    ]
