# Generated by Django 5.2.11 on 2026-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_reviewrequestlead_sent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default='default@clinic.com', max_length=254),
        ),
    ]
