# Generated by Django 5.2.8 on 2026-02-24 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_lead_next_action_type_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='document',
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores Facebook, Instagram, LinkedIn campaign data'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to='restapi.employee'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leads', to='restapi.employee'),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_calls', to='restapi.lead'),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_messages', to='restapi.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='restapi.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_leads', to='restapi.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='slot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='lead_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restapi.lead')),
            ],
            options={
                'db_table': 'restapi_lead_document',
            },
        ),
    ]
