# Generated by Django 5.2.8 on 2026-01-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_alter_parametervalues_equipment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='restapi.task_event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timer_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='IDLE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='environment',
            table='environment',
        ),
        migrations.AlterModelTable(
            name='environment_parameter',
            table='environment_parameter',
        ),
        migrations.CreateModel(
            name='AssigneeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.event')),
            ],
            options={
                'unique_together': {('event', 'assignment')},
            },
        ),
    ]
