# Generated by Django 5.2.8 on 2026-02-02 14:58

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_alter_subtask_status_alter_task_status_and_more'),
    ]

    operations = [
        # NOTE:
        # The unique constraint (event, equipment_details) on EventEquipment
        # already exists in the database from earlier migrations.
        # Hence, AlterUniqueTogether is intentionally removed to avoid
        # DuplicateTable / DuplicateConstraint errors.

        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_description', models.TextField(blank=True)),
                ('campaign_objective', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adv_accounts', models.IntegerField(blank=True, null=True)),
                ('campaign_mode', models.IntegerField(
                    choices=[(1, 'Organic Posting'), (2, 'Paid Advertising')]
                )),
                ('campaign_content', models.TextField(blank=True)),
                ('selected_start', models.DateTimeField()),
                ('selected_end', models.DateTimeField()),
                ('enter_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='campaigns',
                    to='restapi.clinic'
                )),
            ],
        ),

        migrations.CreateModel(
            name='CampaignEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(
                    max_length=255,
                    help_text='Audience list name or identifier'
                )),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='email_configs',
                    to='restapi.campaign'
                )),
            ],
        ),

        migrations.CreateModel(
            name='CampaignSocialMediaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='social_configs',
                    to='restapi.campaign'
                )),
            ],
        ),

        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(
                    max_length=20,
                    choices=[('single', 'Single'), ('married', 'Married')],
                    blank=True,
                    null=True
                )),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('language_preference', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('partner_inquiry', models.BooleanField(default=False)),
                ('partner_full_name', models.CharField(blank=True, max_length=255)),
                ('partner_age', models.IntegerField(blank=True, null=True)),
                ('partner_gender', models.CharField(
                    max_length=10,
                    choices=[('male', 'Male'), ('female', 'Female')],
                    blank=True,
                    null=True
                )),
                ('source', models.CharField(max_length=100)),
                ('sub_source', models.CharField(blank=True, max_length=100)),
                ('lead_status', models.CharField(
                    max_length=20,
                    choices=[('new', 'New'), ('contacted', 'Contacted')],
                    default='new'
                )),
                ('next_action_status', models.CharField(
                    max_length=20,
                    choices=[('pending', 'Pending'), ('completed', 'Completed')],
                    blank=True,
                    null=True
                )),
                ('next_action_description', models.TextField(blank=True, null=True)),
                ('treatment_interest', models.TextField(help_text='Comma separated values')),
                ('document', models.FileField(upload_to='lead_documents/', blank=True, null=True)),
                ('book_appointment', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    related_name='assigned_leads',
                    to='restapi.employee'
                )),
                ('campaign', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    blank=True,
                    related_name='leads',
                    to='restapi.campaign'
                )),
                ('clinic', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='leads',
                    to='restapi.clinic'
                )),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='restapi.department'
                )),
                ('personal', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    related_name='personal_leads',
                    to='restapi.employee'
                )),
            ],
        ),
    ]
