# Generated by Django 5.2.11 on 2026-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_remove_lead_assigned_to_remove_lead_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettimeline',
            name='done_by',
        ),
        migrations.AddField(
            model_name='tickettimeline',
            name='done_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettimeline',
            name='done_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
