# Generated by Django on 2026-02-02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_alter_eventequipment_unique_together_campaign_and_more'),
    ]

    operations = [
        # NO-OP migration
        # Unique constraint (event, equipment_details) already exists in DB.
        # This migration is intentionally left empty to avoid duplicate constraint errors.
    ]
