# Generated by Django 5.2.8 on 2026-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_alter_eventequipment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='eventequipment',
            unique_together={('event', 'equipment_details')},
        ),
    ]
