# Generated by Django 5.2.8 on 2026-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0020_campaign_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
