# Generated by Django 5.2.11 on 2026-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0021_remove_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailconfig',
            name='mailchimp_campaign_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
