# Generated by Django 5.2.11 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_userprofile_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='clinic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clinic',
            field=models.ManyToManyField(blank=True, related_name='users', to='restapi.clinic'),
        ),
    ]
