# Generated by Django 5.2.11 on 2026-04-04 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_remove_userprofile_clinic_userprofile_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='clinic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='restapi.clinic'),
        ),
    ]
