# Generated by Django 5.2.11 on 2026-04-09 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0028_externalclinic_referralsource_lead_referral_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='restapi.lead')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restapi_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0.0)),
                ('sent', models.IntegerField(default=0)),
                ('opened', models.IntegerField(default=0)),
                ('unsubscribed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='restapi.campaign')),
            ],
            options={
                'db_table': 'restapi_campaign_metrics',
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
