# Generated by Django 5.2.11 on 2026-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0029_calllog_campaignmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerule',
            name='custom_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
