# Generated by Django 5.2.11 on 2026-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0029_calllog_campaignmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='li_campaign_urn',
            field=models.CharField(blank=True, help_text='LinkedIn Sponsored Campaign URN (urn:li:sponsoredCampaign:xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialpost',
            name='ads_manager_url',
            field=models.URLField(blank=True, help_text='Direct link to the ad in LinkedIn Campaign Manager', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialpost',
            name='creative_id',
            field=models.CharField(blank=True, help_text='LinkedIn Creative URN', max_length=255, null=True),
        ),
    ]
