# Generated by Django 5.2.11 on 2026-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0030_campaign_li_campaign_urn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='li_ads_account_id',
            field=models.CharField(blank=True, help_text='LinkedIn Ad Account ID (e.g., 123456789)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='linkedin_access_token',
            field=models.TextField(blank=True, help_text='OAuth2 token for LinkedIn API calls', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='campaignsocialmediaconfig',
            unique_together={('campaign', 'platform_name')},
        ),
    ]
