# Generated by Django 5.2.11 on 2026-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0031_campaignsocialmediaconfig_li_ads_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsocialmediaconfig',
            name='li_ads_account_id',
        ),
        migrations.RemoveField(
            model_name='campaignsocialmediaconfig',
            name='linkedin_access_token',
        ),
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='access_token',
            field=models.TextField(blank=True, help_text='OAuth2 token for API calls (LinkedIn, FB, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='platform_account_id',
            field=models.CharField(blank=True, help_text='Platform specific ID (e.g., LinkedIn Ad Account ID or FB Page ID)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='post_id',
            field=models.CharField(blank=True, help_text='Stores post ID or Share URN', max_length=255, null=True),
        ),
    ]
