# Generated by Django 5.2.11 on 2026-04-16 06:51

import restapi.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0031_userprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequestlead',
            name='feedback_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.user_profile.user_profile_photo_upload_to),
        ),
    ]
