# Generated by Django 5.2.11 on 2026-04-16 17:47

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0032_reviewrequestlead_feedback_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralsource',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='referralsource',
            name='type',
        ),
        migrations.AddField(
            model_name='externalclinic',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='external_clinics', to='restapi.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalclinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalclinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='externalclinic',
            table='restapi_external_clinic',
        ),
        migrations.AlterModelTable(
            name='referralsource',
            table='restapi_referral_source',
        ),
        migrations.CreateModel(
            name='ReferralDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_departments', to='restapi.clinic')),
            ],
            options={
                'db_table': 'restapi_referral_department',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='restapi.referraldepartment'),
        ),
        migrations.AddField(
            model_name='referralsource',
            name='referral_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_sources', to='restapi.referraldepartment'),
        ),
        migrations.AddIndex(
            model_name='referraldepartment',
            index=models.Index(fields=['clinic', 'name'], name='restapi_ref_clinic__b23a96_idx'),
        ),
        migrations.AddConstraint(
            model_name='referraldepartment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('clinic'), name='unique_referral_department_per_clinic_ci'),
        ),
    ]
