# Generated by Django 5.2.11 on 2026-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0032_remove_campaignsocialmediaconfig_li_ads_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
