# Generated by Django 5.2.11 on 2026-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0033_alter_referralsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
