# Generated by Django 5.2.11 on 2026-04-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0033_alter_referralsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='restapi.pipelinestage'),
        ),
    ]
