# Generated by Django 5.2.11 on 2026-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0033_alter_campaignsocialmediaconfig_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
