# Generated by Django 5.2.11 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_socialaccount_expires_at_socialaccount_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='campaign_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='org_urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
