# Generated by Django 5.2.11 on 2026-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_socialaccount_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='insights',
            field=models.JSONField(blank=True, help_text='Stores campaign insights fetched from social media platforms', null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='platform_name',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('google_ads', 'Google Ads')], max_length=50),
        ),
    ]
