# Generated by Django 5.2.11 on 2026-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_lead_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralsource',
            name='id',
        ),
        migrations.AlterField(
            model_name='referralsource',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
