# Generated by Django 5.2.11 on 2026-04-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0035_remove_referralsource_id_alter_referralsource_email"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE restapi_referral_source "
                "DROP CONSTRAINT IF EXISTS restapi_referral_source_email_defd8740_pk;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="referralsource",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="referralsource",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="referral_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="restapi.referralsource",
            ),
        ),
    ]
