# Generated by Django 5.2.11 on 2026-04-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0035_socialaccount_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='li_campaign_urn',
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_metrics_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_synced_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Cached metrics from insights sync'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_account_id',
            field=models.CharField(blank=True, help_text='LinkedIn ad account id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_ads_manager_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_campaign_group_urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_campaign_urn',
            field=models.CharField(blank=True, help_text='urn:li:sponsoredCampaign:xxx', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_creative_id',
            field=models.CharField(blank=True, help_text='Numeric LinkedIn creative id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_creative_urn',
            field=models.CharField(blank=True, help_text='urn:li:sponsoredCreative:xxx', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_external_campaign_id',
            field=models.CharField(blank=True, db_index=True, help_text='Numeric LinkedIn campaign id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_post_urn',
            field=models.CharField(blank=True, help_text='Sponsored post URN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkedin_raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw LinkedIn API create callback payload'),
        ),
    ]
