# Generated by Django 5.2.11 on 2026-04-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0035_campaignsocialmediaconfig_insights_and_more'),
        ('restapi', '0036_referralsource_id_alter_referralsource_email'),
    ]

    operations = [
    ]
