# Generated by Django 5.2.11 on 2026-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0036_remove_campaign_li_campaign_urn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='linkedin_live_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
