# Generated by Django 5.2.11 on 2026-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0037_merge_20260422_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_action_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
