# Generated by Django 5.2.11 on 2026-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0038_alter_lead_lead_status_alter_lead_next_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='next_action_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
