# Generated by Django 5.2.11 on 2026-04-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0037_campaign_linkedin_live_status'),
        ('restapi', '0040_lead_contact_designation_lead_contact_email_and_more'),
    ]

    operations = [
    ]
