# Generated by Django 5.2.11 on 2026-04-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0041_merge_20260425_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignsocialmediaconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaignsocialmediaconfig',
            name='insights',
        ),
    ]
