# Generated by Django 5.2.11 on 2026-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0042_alter_campaignsocialmediaconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
