# Generated by Django 5.2.11 on 2026-04-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0043_alter_lead_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademail',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_emails', to='restapi.clinic'),
        ),
    ]
