# Generated by Django 5.2.11 on 2026-04-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0044_leademail_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_calls', to='restapi.clinic'),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_messages', to='restapi.clinic'),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('busy', 'Busy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['clinic'], name='twilio_call_clinic__fb256b_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['sid'], name='twilio_call_sid_a41693_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliomessage',
            index=models.Index(fields=['clinic'], name='twilio_mess_clinic__1acf63_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliomessage',
            index=models.Index(fields=['sid'], name='twilio_mess_sid_6b887e_idx'),
        ),
    ]
