# Generated by Django 5.2.11 on 2026-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0045_twiliocall_clinic_twiliomessage_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsocialmediaconfig',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='campaignsocialmediaconfig',
            name='platform_account_id',
        ),
        migrations.AddField(
            model_name='campaignsocialmediaconfig',
            name='insights',
            field=models.JSONField(blank=True, help_text='Stores campaign insights fetched from social media platforms', null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='post_id',
            field=models.CharField(blank=True, help_text='Stores social media post ID', max_length=255, null=True),
        ),
    ]
