# Generated by Django 5.2.11 on 2026-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0046_remove_campaignsocialmediaconfig_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialmediaconfig',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='campaignsocialmediaconfig',
            unique_together={('campaign', 'platform_name')},
        ),
    ]
