# Generated by Django 5.2.11 on 2026-04-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0047_alter_campaignsocialmediaconfig_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='restapi.pipelinestage'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='is_conversion_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='is_default_stage',
            field=models.BooleanField(default=False),
        ),
    ]
