# Generated by Django 5.2.11 on 2026-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0048_lead_converted_at_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='treatment_interest',
            field=models.TextField(),
        ),
    ]
