# Generated by Django 5.2.11 on 2026-04-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0049_alter_lead_treatment_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
