# Generated by Django 5.2.11 on 2026-04-30 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0050_lead_converted_at_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='review_request_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restapi.reviewrequest')),
            ],
            options={
                'db_table': 'restapi_review_request_document',
            },
        ),
    ]
