# Generated by Django 5.2.11 on 2026-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0050_lead_converted_at_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignmetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='ads_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='ctr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('google', 'Google'), ('email', 'Email')], default='linkedin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='raw_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='video_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetrics',
            unique_together={('campaign', 'platform', 'date')},
        ),
    ]
