# Generated by Django 5.2.11 on 2026-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0051_reviewrequestdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
