# Generated by Django 5.2.11 on 2026-05-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0051_alter_campaignmetrics_unique_together_and_more'),
        ('restapi', '0052_clinic_is_active'),
    ]

    operations = [
    ]
