# Generated by Django 5.2.11 on 2026-05-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0053_merge_20260502_1457'),
        ('restapi', '0053_merge_20260502_1522'),
    ]

    operations = [
    ]
