# Generated by Django 5.2.11 on 2026-05-05 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0054_merge_20260503_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecases', to='restapi.clinic')),
            ],
            options={
                'db_table': 'restapi_usecase',
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates', to='restapi.usecase'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='restapi.clinic')),
            ],
            options={
                'db_table': 'restapi_interest',
                'unique_together': {('clinic', 'name')},
            },
        ),
    ]
