# Generated by Django 5.2.11 on 2026-05-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0057_alter_templatemail_use_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesms',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.usecase'),
        ),
    ]
