# Generated by Django 5.2.11 on 2026-05-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0059_alter_templatesms_use_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemail',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_templates', to='restapi.usecase'),
        ),
    ]
