# Generated by Django 5.2.11 on 2026-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0060_alter_templatemail_use_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='treatment_interest',
        ),
        migrations.AddField(
            model_name='lead',
            name='treatment_interest',
            field=models.ManyToManyField(blank=True, related_name='leads', to='restapi.interest'),
        ),
    ]
