# Generated by Django 5.2.11 on 2026-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0061_remove_lead_treatment_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='treatment_interest_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
