# Generated by Django 5.2.11 on 2026-05-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0062_lead_treatment_interest_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='treatment_interest_names',
        ),
    ]
