# Generated by Django 5.2.11 on 2026-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0063_remove_lead_treatment_interest_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='action_status',
            field=models.CharField(blank=True, choices=[('to_do', 'To-do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
