# Generated by Django 5.2.11 on 2026-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0064_lead_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliocall',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('canceled', 'Canceled')], max_length=50, null=True),
        ),
    ]
