# Generated by Django 5.2.11 on 2026-05-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0064_lead_action_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=100)),
                ('category_key', models.CharField(max_length=100)),
                ('subcategory_key', models.CharField(blank=True, max_length=100, null=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='restapi_use_user_id_c98361_idx'), models.Index(fields=['module_key'], name='restapi_use_module__02d65f_idx'), models.Index(fields=['category_key'], name='restapi_use_categor_5948c1_idx')],
                'unique_together': {('user', 'module_key', 'category_key', 'subcategory_key')},
            },
        ),
    ]
