# Generated by Django 5.2.11 on 2026-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0065_alter_twiliocall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='answered_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='call_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='was_answered',
            field=models.BooleanField(default=False),
        ),
    ]
