# Generated by Django 5.2.11 on 2026-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0065_add_user_permission_model'),
        ('restapi', '0066_twiliocall_answered_by_twiliocall_call_duration_and_more'),
    ]

    operations = [
    ]
