# Generated by Django 5.2.11 on 2026-05-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0067_merge_20260508_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_template_id', models.CharField(blank=True, help_text='Template ID returned by Meta Graph API', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='Template name (lowercase, underscores only)', max_length=255)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=50)),
                ('language', models.CharField(default='en', help_text='BCP-47 language code e.g. en, en_US, hi', max_length=20)),
                ('header_text', models.CharField(blank=True, default='', max_length=60)),
                ('body_text', models.TextField(help_text='Message body with {{1}}, {{2}} placeholders')),
                ('footer_text', models.CharField(blank=True, default='', max_length=60)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], db_index=True, default='PENDING', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='whatsapp_te_status_7920c7_idx'), models.Index(fields=['name', 'language'], name='whatsapp_te_name_67a703_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=30)),
                ('to_number', models.CharField(max_length=30)),
                ('template_name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=20)),
                ('variable_values', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], db_index=True, default='queued', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='restapi.clinic')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='restapi.lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='restapi.whatsapptemplate')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic'], name='whatsapp_me_clinic__3586fd_idx'), models.Index(fields=['sid'], name='whatsapp_me_sid_dc97e5_idx'), models.Index(fields=['status'], name='whatsapp_me_status_63922d_idx'), models.Index(fields=['to_number'], name='whatsapp_me_to_numb_2c6a97_idx')],
            },
        ),
    ]
