# Generated by Django 5.2.11 on 2026-05-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0068_whatsapptemplate_whatsappmessage'),
    ]

    operations = [

        # Remove old FK constraint
        migrations.RunSQL(
            sql="""
                ALTER TABLE whatsapp_messages
                DROP CONSTRAINT IF EXISTS whatsapp_messages_template_id_55642918_fk_whatsapp_templates_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Remove old bigint column completely
        migrations.RunSQL(
            sql="""
                ALTER TABLE whatsapp_messages
                DROP COLUMN IF EXISTS template_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Recreate as UUID FK correctly
        migrations.AddField(
            model_name='whatsappmessage',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='whatsapp_messages',
                to='restapi.templatewhatsapp',
            ),
        ),

        # Delete old model
        migrations.DeleteModel(
            name='WhatsAppTemplate',
        ),
    ]