# Generated by Django 5.2.11 on 2026-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0069_alter_whatsappmessage_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsocialpost',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaignsocialpost',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_documents/'),
        ),
        migrations.AlterField(
            model_name='campaignsocialpost',
            name='ads_manager_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialpost',
            name='creative_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialpost',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialpost',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaignsocialpost',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
