# Generated by Django 5.2.11 on 2026-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0070_campaignsocialpost_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='instagram_campaign_id',
            field=models.CharField(blank=True, help_text='Instagram Ad Campaign ID created via API', max_length=100, null=True),
        ),
    ]
