# Generated by Django 5.2.11 on 2026-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0073_pipeline_default_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='google_campaign_id',
            field=models.CharField(blank=True, help_text='Google Ad Campaign ID created via API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_campaign_resource_name',
            field=models.CharField(blank=True, help_text='Google Campaign Resource Name created via API', max_length=500, null=True),
        ),
    ]
