# Generated by Django 5.2.11 on 2026-05-22 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0074_campaign_google_campaign_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStageAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_id', models.UUIDField()),
                ('stage_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_audit_logs', to='restapi.pipeline')),
            ],
            options={
                'db_table': 'restapi_pipeline_stage_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
