# Generated by Django 5.2.11 on 2026-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0075_pipelinestageauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_patient_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_patient_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
