# Generated by Django 5.2.11 on 2026-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0076_lead_external_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestageauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
