# Generated by Django 5.2.11 on 2026-06-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0077_alter_pipelinestageauditlog_action"),
    ]

    operations = [
        # First, clean up orphaned referral_source_ids
        migrations.RunSQL(
            sql="""
            UPDATE restapi_lead
            SET referral_source_id = NULL
            WHERE referral_source_id IS NOT NULL
            AND referral_source_id NOT IN (
                SELECT id FROM restapi_referral_source
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Then add the foreign key constraint
        migrations.RunSQL(
            sql="""
            ALTER TABLE restapi_lead
            ADD CONSTRAINT restapi_lead_referral_source_id_fkey
            FOREIGN KEY (referral_source_id)
            REFERENCES restapi_referral_source(id)
            ON DELETE SET NULL;
            """,
            reverse_sql="""
            ALTER TABLE restapi_lead
            DROP CONSTRAINT IF EXISTS restapi_lead_referral_source_id_fkey;
            """,
        ),
    ]

