# Generated by Django 5.2.11 on 2026-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0078_add_referral_source_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leademail',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RECEIVED', 'Received')], default='DRAFT', max_length=20),
        ),
    ]
