from django.db import migrations, models
import uuid


LEAD_FORM_FIELDS = [
    ("full_name", "full_name", "Lead Name / Lab Name", "text", "", 1, "Lead Details", 10, True, True),
    ("contact_no", "contact_no", "Contact Number", "phone", "", 1, "Lead Details", 20, False, False),
    ("email", "email", "Email", "email", "", 1, "Lead Details", 30, False, False),
    ("location", "location", "Location", "text", "", 1, "Lead Details", 40, False, False),
    ("gender", "gender", "Gender", "dropdown", "gender", 1, "Lead Details", 50, False, False),
    ("age", "age", "Age", "number", "", 1, "Lead Details", 60, False, False),
    ("marital_status", "marital_status", "Marital Status", "dropdown", "marital_status", 1, "Lead Details", 70, False, False),
    ("address", "address", "Address", "textarea", "", 1, "Lead Details", 80, False, False),
    ("language_preference", "language_preference", "Language Preference", "dropdown", "language", 1, "Lead Details", 90, False, False),
    ("contact_full_name", "contact_full_name", "Contact Full Name", "text", "", 1, "Contact Person", 100, False, False),
    ("contact_designation", "contact_designation", "Designation", "text", "", 1, "Contact Person", 110, False, False),
    ("contact_phone", "contact_phone", "Contact Phone", "phone", "", 1, "Contact Person", 120, False, False),
    ("contact_email", "contact_email", "Contact Email", "email", "", 1, "Contact Person", 130, False, False),
    ("lead_generated_by", "", "Lead Generated By", "dropdown", "employees", 1, "Source", 140, False, False),
    ("source", "source", "Source", "dropdown", "lead_source", 1, "Source", 150, False, False),
    ("sub_source", "sub_source", "Sub Source", "dropdown", "lead_sub_source", 1, "Source", 160, False, False),
    ("campaign", "", "Campaign", "dropdown", "campaigns", 1, "Source", 170, False, False),
    ("assigned_to_id", "assigned_to_id", "Assigned To", "dropdown", "employees", 1, "Ownership", 180, True, True),
    ("lead_status", "lead_status", "Lead Status", "dropdown", "pipeline_stages", 1, "Pipeline", 190, False, False),
    ("next_action_status", "next_action_status", "Next Action Status", "dropdown", "pipeline_stages", 1, "Pipeline", 200, False, False),
    ("next_action_type", "next_action_type", "Next Action Type", "dropdown", "stage_actions", 1, "Pipeline", 210, False, False),
    ("next_action_description", "next_action_description", "Next Action Description", "textarea", "", 1, "Pipeline", 220, False, False),
    ("action_status", "action_status", "Task Status", "dropdown", "task_status", 1, "Pipeline", 230, False, False),
    ("referral_department", "referral_department", "Referral Department", "dropdown", "referral_departments", 1, "Referral", 240, False, False),
    ("treatment_interest", "treatment_interest", "Product Interest", "multi_select", "interests", 2, "Interest", 250, True, True),
    ("documents", "", "Documents", "file", "", 2, "Documents", 260, False, False),
    ("book_appointment", "book_appointment", "Book Appointment", "boolean", "", 3, "Appointment", 270, False, False),
    ("department", "department", "Department", "dropdown", "departments", 3, "Appointment", 280, False, False),
    ("personal_id", "personal_id", "Personnel", "dropdown", "employees", 3, "Appointment", 290, False, False),
    ("appointment_date", "appointment_date", "Appointment Date", "date", "", 3, "Appointment", 300, False, False),
    ("slot", "slot", "Slot", "dropdown", "appointment_slots", 3, "Appointment", 310, False, False),
    ("remark", "remark", "Remark", "textarea", "", 3, "Appointment", 320, False, False),
    ("partner_full_name", "partner_full_name", "Partner Full Name", "text", "", 1, "Partner Details", 330, False, False),
    ("partner_age", "partner_age", "Partner Age", "number", "", 1, "Partner Details", 340, False, False),
    ("partner_gender", "partner_gender", "Partner Gender", "dropdown", "gender", 1, "Partner Details", 350, False, False),
]


def seed_lead_form_fields(apps, schema_editor):
    LeadFormField = apps.get_model("restapi", "LeadFormField")
    for (
        field_key,
        model_field,
        field_label,
        field_type,
        options_source,
        form_step,
        section,
        sort_order,
        is_required,
        is_locked,
    ) in LEAD_FORM_FIELDS:
        LeadFormField.objects.update_or_create(
            field_key=field_key,
            defaults={
                "model_field": model_field,
                "field_label": field_label,
                "field_type": field_type,
                "options_source": options_source,
                "form_step": form_step,
                "section": section,
                "sort_order": sort_order,
                "is_required": is_required,
                "is_locked": is_locked,
                "is_active": True,
            },
        )


def unseed_lead_form_fields(apps, schema_editor):
    LeadFormField = apps.get_model("restapi", "LeadFormField")
    LeadFormField.objects.filter(field_key__in=[field[0] for field in LEAD_FORM_FIELDS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0079_alter_leademail_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadFormField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field_key", models.CharField(max_length=100, unique=True)),
                ("model_field", models.CharField(blank=True, default="", max_length=100)),
                ("field_label", models.CharField(max_length=150)),
                ("field_type", models.CharField(choices=[("text", "Text"), ("number", "Number"), ("date", "Date"), ("dropdown", "Dropdown"), ("textarea", "Textarea"), ("email", "Email"), ("phone", "Phone"), ("multi_select", "Multi Select"), ("boolean", "Boolean"), ("file", "File")], default="text", max_length=30)),
                ("options_source", models.CharField(blank=True, default="", max_length=100)),
                ("form_step", models.PositiveSmallIntegerField(default=1)),
                ("section", models.CharField(blank=True, default="", max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "restapi_lead_form_field",
                "ordering": ["sort_order", "field_label"],
            },
        ),
        migrations.AddField(
            model_name="stagefield",
            name="field_key",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="leadformfield",
            index=models.Index(fields=["field_key"], name="restapi_lea_field_k_123c9d_idx"),
        ),
        migrations.AddIndex(
            model_name="leadformfield",
            index=models.Index(fields=["is_active", "sort_order"], name="restapi_lea_is_acti_eea05a_idx"),
        ),
        migrations.RunPython(seed_lead_form_fields, unseed_lead_form_fields),
    ]
