"""
Lead Visibility Tests: Role-based access to leads

Tests the lead visibility scope enforcement for different user roles:
- Users can see only their own created leads or leads generated by them
- Admins can see all leads in their clinic
- Super admins can see all leads in their clinic
"""

from django.test import TestCase
from django.contrib.auth.models import User
from django.db.models import Q

from restapi.models import Clinic, Department, Lead, UserProfile, Role, Employee


class LeadVisibilityTestCase(TestCase):
    """Test role-based lead visibility enforcement at the queryset level"""

    def setUp(self):
        """Set up test fixtures: clinics, roles, users, leads"""
        # ====== CLINICS ======
        self.clinic1 = Clinic.objects.create(name="Clinic Alpha")
        self.clinic2 = Clinic.objects.create(name="Clinic Beta")

        # ====== DEPARTMENTS ======
        self.dept1 = Department.objects.create(
            name="IVF", clinic=self.clinic1, is_active=True
        )
        self.dept2 = Department.objects.create(
            name="Cardiology", clinic=self.clinic2, is_active=True
        )

        # ====== ROLES ======
        self.role_user = Role.objects.create(name="user")
        self.role_admin = Role.objects.create(name="admin")
        self.role_superadmin = Role.objects.create(name="super_admin")

        # ====== USERS & PROFILES ======
        # User 1: restricted user at clinic1
        self.user1 = User.objects.create_user(
            username="user1", password="pass123", email="user1@test.com"
        )
        self.profile1, _ = UserProfile.objects.get_or_create(
            user=self.user1, defaults={"role": self.role_user, "clinic": self.clinic1}
        )
        self.emp1 = Employee.objects.create(
            clinic=self.clinic1, department=self.dept1, user=self.user1, emp_name="User One", emp_type="staff"
        )

        # User 2: another restricted user at clinic1
        self.user2 = User.objects.create_user(
            username="user2", password="pass123", email="user2@test.com"
        )
        self.profile2, _ = UserProfile.objects.get_or_create(
            user=self.user2, defaults={"role": self.role_user, "clinic": self.clinic1}
        )
        self.emp2 = Employee.objects.create(
            clinic=self.clinic1, department=self.dept1, user=self.user2, emp_name="User Two", emp_type="staff"
        )

        # Admin: clinic1
        self.admin = User.objects.create_user(
            username="admin1", password="pass123", email="admin@test.com"
        )
        self.admin_profile, _ = UserProfile.objects.get_or_create(
            user=self.admin, defaults={"role": self.role_admin, "clinic": self.clinic1}
        )
        self.admin_emp = Employee.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            user=self.admin,
            emp_name="Admin One",
            emp_type="admin",
        )

        # Super Admin: clinic1
        self.superadmin = User.objects.create_user(
            username="superadmin1", password="pass123", email="sa@test.com"
        )
        self.superadmin_profile, _ = UserProfile.objects.get_or_create(
            user=self.superadmin,
            defaults={
                "role": self.role_superadmin,
                "clinic": self.clinic1,
            },
        )
        self.superadmin_emp = Employee.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            user=self.superadmin,
            emp_name="Super Admin",
            emp_type="superadmin",
        )

        # ====== LEADS ======
        # Lead 1: created by user1
        self.lead1 = Lead.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            full_name="Lead 1",
            contact_no="9111111111",
            source="Direct",
            treatment_interest="IVF",
            created_by_id=self.emp1.id,
            created_by_name="User One",
        )

        # Lead 2: created by user2
        self.lead2 = Lead.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            full_name="Lead 2",
            contact_no="9222222222",
            source="Direct",
            treatment_interest="IVF",
            created_by_id=self.emp2.id,
            created_by_name="User Two",
        )

        # Lead 3: created by user1, but generated by user2 (personal_id = emp2.id)
        self.lead3 = Lead.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            full_name="Lead 3",
            contact_no="9333333333",
            source="Referral",
            treatment_interest="IVF",
            created_by_id=self.emp1.id,
            created_by_name="User One",
            personal_id=self.emp2.id,
            personal_name="User Two",
        )

        # Lead 4: created by user2, but generated by user1 (personal_id = emp1.id)
        self.lead4 = Lead.objects.create(
            clinic=self.clinic1,
            department=self.dept1,
            full_name="Lead 4",
            contact_no="9444444444",
            source="Referral",
            treatment_interest="IVF",
            created_by_id=self.emp2.id,
            created_by_name="User Two",
            personal_id=self.emp1.id,
            personal_name="User One",
        )

        # Lead 5: at clinic2 (should not be visible to clinic1 users)
        self.lead5 = Lead.objects.create(
            clinic=self.clinic2,
            department=self.dept2,
            full_name="Lead 5 Clinic 2",
            contact_no="9555555555",
            source="Direct",
            treatment_interest="Cardiology",
            created_by_id=self.emp1.id,
            created_by_name="User One",
        )

    def apply_user_visibility_filter(self, user):
        """
        Simulate the backend visibility scope logic for a user.
        Returns filtered leads based on user role and created_by/personal_id.
        """
        # Determine if user is restricted (role is "user")
        is_restricted = user.profile.role.name == "user"

        # Get base clinic leads
        queryset = Lead.objects.filter(clinic=user.profile.clinic)

        if not is_restricted:
            # Admins and super_admins see all clinic leads
            return queryset

        # For restricted users: collect candidate IDs (user.id and employee.id)
        candidate_ids = set()
        
        # Add user.id if available
        if user.id:
            candidate_ids.add(user.id)

        # Add employee.id if employee exists
        try:
            employee = Employee.objects.get(user=user, clinic=user.profile.clinic)
            if employee.id:
                candidate_ids.add(employee.id)
        except Employee.DoesNotExist:
            pass

        # Filter: created by user OR personal_id matches user
        return queryset.filter(
            Q(created_by_id__in=candidate_ids) | Q(personal_id__in=candidate_ids)
        )

    def test_user1_sees_own_created_leads(self):
        """User can see leads they created"""
        visible_leads = self.apply_user_visibility_filter(self.user1)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User1 should see lead1 (created by user1)
        self.assertIn(self.lead1.id, visible_lead_ids)

    def test_user1_sees_leads_generated_by_them(self):
        """User can see leads where they are 'Lead Generated By' (personal_id)"""
        visible_leads = self.apply_user_visibility_filter(self.user1)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User1 should see lead4 (personal_id = emp1.id)
        self.assertIn(self.lead4.id, visible_lead_ids)

    def test_user1_cannot_see_others_leads(self):
        """User cannot see leads created by others unless they generated them"""
        visible_leads = self.apply_user_visibility_filter(self.user1)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User1 should NOT see lead2 (created by user2, user1 is not personal_id)
        self.assertNotIn(self.lead2.id, visible_lead_ids)

    def test_user2_sees_own_and_generated_leads(self):
        """User2 should see leads they created and leads they generated"""
        visible_leads = self.apply_user_visibility_filter(self.user2)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User2 should see:
        # - lead2 (created by user2)
        # - lead3 (personal_id = emp2.id, generated by user2)
        self.assertIn(self.lead2.id, visible_lead_ids)
        self.assertIn(self.lead3.id, visible_lead_ids)

        # User2 should NOT see:
        # - lead1 (created by user1, user2 is not personal_id)
        self.assertNotIn(self.lead1.id, visible_lead_ids)

    def test_admin_sees_all_clinic_leads(self):
        """Admin should see all leads in their clinic"""
        visible_leads = self.apply_user_visibility_filter(self.admin)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # Admin should see all 4 clinic1 leads
        self.assertIn(self.lead1.id, visible_lead_ids)
        self.assertIn(self.lead2.id, visible_lead_ids)
        self.assertIn(self.lead3.id, visible_lead_ids)
        self.assertIn(self.lead4.id, visible_lead_ids)

        # Admin should NOT see clinic2 leads (clinic boundary)
        self.assertNotIn(self.lead5.id, visible_lead_ids)

    def test_superadmin_sees_all_clinic_leads(self):
        """Super Admin should see all leads in their clinic"""
        visible_leads = self.apply_user_visibility_filter(self.superadmin)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # Super Admin should see all 4 clinic1 leads
        self.assertIn(self.lead1.id, visible_lead_ids)
        self.assertIn(self.lead2.id, visible_lead_ids)
        self.assertIn(self.lead3.id, visible_lead_ids)
        self.assertIn(self.lead4.id, visible_lead_ids)

        # Super Admin should NOT see clinic2 leads (clinic boundary)
        self.assertNotIn(self.lead5.id, visible_lead_ids)

    def test_clinic_boundary_enforcement(self):
        """Clinic boundary should prevent access to leads from other clinics"""
        # Get leads for clinic2 using clinic1 user (should be filtered at queryset level)
        visible_leads = self.apply_user_visibility_filter(self.user1)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User1 at clinic1 should NOT see clinic2 leads
        self.assertNotIn(self.lead5.id, visible_lead_ids)

    def test_user_lead_count_matches_visibility(self):
        """User sees exactly the leads they should have access to"""
        visible_leads = self.apply_user_visibility_filter(self.user1)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # User1 should see exactly 3 leads:
        # - lead1 (created_by_id = emp1.id)
        # - lead3 (created_by_id = emp1.id)
        # - lead4 (personal_id = emp1.id)
        self.assertEqual(len(visible_lead_ids), 3)
        
        self.assertIn(self.lead1.id, visible_lead_ids)
        self.assertIn(self.lead3.id, visible_lead_ids)
        self.assertIn(self.lead4.id, visible_lead_ids)

    def test_admin_lead_count_clinic_boundary(self):
        """Admin sees all clinic leads but respects clinic boundary"""
        visible_leads = self.apply_user_visibility_filter(self.admin)
        visible_lead_ids = set(visible_leads.values_list('id', flat=True))

        # Admin should see exactly 4 clinic1 leads (not clinic2 lead)
        self.assertEqual(len(visible_lead_ids), 4)
        
        self.assertIn(self.lead1.id, visible_lead_ids)
        self.assertIn(self.lead2.id, visible_lead_ids)
        self.assertIn(self.lead3.id, visible_lead_ids)
        self.assertIn(self.lead4.id, visible_lead_ids)
        
        # Clinic2 lead should be filtered by clinic queryset
        self.assertNotIn(self.lead5.id, visible_lead_ids)
