name: VIDAI-LMS-SERVICES Push Trigger

on:
  push:
    branches:
      - main
      - devops-build
      #- googleads_feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f devops/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

            echo "Stop old container"
            docker ps -aq --filter "name=vidai-backend" | xargs -r docker stop
            docker ps -aq --filter "name=vidai-backend" | xargs -r docker rm

            echo "Start new container"
            docker run -d \
              --restart always \
              --name vidai-backend \
              -p 8004:8000 \
              --add-host=host.docker.internal:host-gateway \
              -e EMAIL_BACKEND="${{ secrets.EMAIL_BACKEND }}" \
              -e EMAIL_HOST="${{ secrets.EMAIL_HOST }}" \
              -e EMAIL_PORT="${{ secrets.EMAIL_PORT }}" \
              -e EMAIL_USE_TLS="${{ secrets.EMAIL_USE_TLS }}" \
              -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
              -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
              -e FACEBOOK_CLIENT_ID="${{ secrets.FACEBOOK_CLIENT_ID }}" \
              -e FACEBOOK_CLIENT_SECRET="${{ secrets.FACEBOOK_CLIENT_SECRET }}" \
              -e FACEBOOK_REDIRECT_URI="${{ secrets.FACEBOOK_REDIRECT_URI }}" \
              -e FB_ACCESS_TOKEN="${{ secrets.FB_ACCESS_TOKEN }}" \
              -e FB_AD_ACCOUNT_ID="${{ secrets.FB_AD_ACCOUNT_ID }}" \
              -e FRONTEND_BASE_URL="${{ secrets.FRONTEND_BASE_URL }}" \
              -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
              -e LINKEDIN_CLIENT_ID="${{ secrets.LINKEDIN_CLIENT_ID }}" \
              -e LINKEDIN_CLIENT_SECRET="${{ secrets.LINKEDIN_CLIENT_SECRET }}" \
              -e LINKEDIN_REDIRECT_URI="${{ secrets.LINKEDIN_REDIRECT_URI }}" \
              -e MAILCHIMP_API_KEY="${{ secrets.MAILCHIMP_API_KEY }}" \
              -e MAILCHIMP_AUDIENCE_ID="${{ secrets.MAILCHIMP_AUDIENCE_ID }}" \
              -e MAILCHIMP_DATA_CENTER="${{ secrets.MAILCHIMP_DATA_CENTER }}" \
              -e MAILCHIMP_EMAIL_LIST_ID="${{ secrets.MAILCHIMP_EMAIL_LIST_ID }}" \
              -e MAILCHIMP_SENDER_EMAIL="${{ secrets.MAILCHIMP_SENDER_EMAIL }}" \
              -e MAILCHIMP_SERVER="${{ secrets.MAILCHIMP_SERVER }}" \
              -e TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}" \
              -e TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
              -e TWILIO_PHONE_NUMBER="${{ secrets.TWILIO_PHONE_NUMBER }}" \
              -e ZAPIER_WEBHOOK_FB_INSIGHTS_URL="${{ secrets.ZAPIER_WEBHOOK_FB_INSIGHTS_URL }}" \
              -e ZAPIER_WEBHOOK_TWILIO_URL="${{ secrets.ZAPIER_WEBHOOK_TWILIO_URL }}" \
              -e STAGE_PROFILE_URL="${{ secrets.STAGE_PROFILE_URL }}" \
              -e STAGE_LOGIN_URL="${{ secrets.STAGE_LOGIN_URL }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e GOOGLE_ADS_DEVELOPER_TOKEN="${{ secrets.GOOGLE_ADS_DEVELOPER_TOKEN }}" \
              -e GOOGLE_ADS_LOGIN_CUSTOMER_ID="${{ secrets.GOOGLE_ADS_LOGIN_CUSTOMER_ID }}" \
              -e GOOGLE_REDIRECT_URI="${{ secrets.GOOGLE_REDIRECT_URI }}" \
              -e GOOGLE_ACCESS_TOKEN="${{ secrets.GOOGLE_ACCESS_TOKEN }}" \
              -e GOOGLE_REFRESH_TOKEN="${{ secrets.GOOGLE_REFRESH_TOKEN }}" \
              -e ZAPIER_WEBHOOK_SOCIAL_URL="${{ secrets.ZAPIER_WEBHOOK_SOCIAL_URL }}" \
              -e ZAPIER_WEBHOOK_GOOGLE_ADS_URL="${{ secrets.ZAPIER_WEBHOOK_GOOGLE_ADS_URL }}" \
              -e TWILIO_BRIDGE_NUMBER="${{ secrets.TWILIO_BRIDGE_NUMBER }}" \
              -e TWILIO_SMS_STATUS_CALLBACK_URL="${{ secrets.TWILIO_SMS_STATUS_CALLBACK_URL }}" \
              -e TWILIO_CALL_STATUS_CALLBACK_URL="${{ secrets.TWILIO_CALL_STATUS_CALLBACK_URL }}" \
              -e ZAPIER_WEBHOOK_INSIGHTS_URL="${{ secrets.ZAPIER_WEBHOOK_INSIGHTS_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/vidai-backend:latest

            echo "Wait container boot"
            sleep 12
                   
            echo "Run database migrations"
            docker exec vidai-backend python manage.py migrate || true
